spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc.time_zone: Asia/Seoul
    open-in-view: false

  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000


firebase:
  credential-path: ${FIREBASE_CREDENTIAL_PATH}

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
  kakao:
    app-id: ${KAKAO_APP_ID}

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug
    com.feellog: DEBUG